services:
   doc_extractor:
      build:
         context: .
         dockerfile: Dockerfile_extractor
      image: doc-extractor:latest
      container_name: doc_extractor
      ports:
         - "7643:7643"
      volumes:
         - ./app.py:/app/app.py
         - ./frontend:/app/frontend
      environment:
         - MAX_UPLOAD_MB=20
      restart: unless-stopped
